apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lab06apictactehpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab06apictactebus
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50
